### ISSUE TITLE
Command to list installed contributions

### ISSUE THREAD

**Issue by fcastill** [project-flogo/cli#10]
A command to list the contributions that are installed in a project so they could be inspected.

Expecting something like:

`flogo list -json`

And that lists in a json format for each contribution:

1. name and/or package ref
2. type of the contribution (activity, trigger, etc.)
3. path to descriptor.json for further inspection

**Comment by skothari-tibco** [comment]
Hey Fabian,
Currently the fields displayed by the commands are as follows. Please let me know if you would like to have any other fields. 
```json 
{
      "name": "sample-trigger",
      "type": "flogo:trigger",
      "version": "0.0.1",
      "description": "Sample Azure Trigger",
      "ref": "",
      "shim": "main"
}
```
Thanks

**Comment by fcastill** [comment]
I'm actually interested in the full descriptor.json so I can use the attributes to render the UI. Is it possible to have something like the following so in the UI side we can use each `contribution.descriptor` to locate the descriptors in the filesystem?:

```jsonc
[
  {
    "type": "activity", // or flogo:activity
    "ref": "github.com/TIBCOSoftware/project-flogo/contrib/activity/log"
    "descriptor": "/path/to/github.com/project-flogo/contrib@0.5.0/activity/log/descriptor.json",
  },
  {
    "type": "trigger", // or flogo:trigger
    "ref": "github.com/TIBCOSoftware/project-flogo/contrib/trigger/rest",
    "descriptor": "/path/to/github.com/project-flogo/contrib@v0.5.0/trigger/actreturn/descriptor.json",
  }
]
```

**Comment by skothari-tibco** [comment]
Yes, it is possible.
