### ISSUE TITLE
Maintain Version while creating Flogo Application from CLI

### ISSUE THREAD

**Issue by akpuvvada** [project-flogo/cli#100]
If I want to use the same version of Flogo every time I build an application, is there a way to specify the version to use in Application JSON or in CLI Command?

Looks like, the 'flogo create' command always get the latest from GIT to build an application.
After every bug-fix or code change, I don't want the version change (both GO and Flogo) which may potentially introduce new unknown issues.

**Comment by skothari-tibco** [comment]
During the flogo create it will always get the latest tagged version of the contributions unless a version is specified . If you would like to get the version you want; you can add that version in the `imports [ ]` section of the JSON. Eg . 

```
"imports": [
    "github.com/project-flogo/flow@v0.9.4",
    "github.com/project-flogo/contrib/activity/actreturn@v0.9.0",
    "github.com/project-flogo/contrib/activity/log@latest",
    "github.com/project-flogo/contrib/function/string"
  ]
``` .

**Comment by akpuvvada** [comment]
Thanks, Samip. How do I check what version do I have installed currently of each of the entries?

**Comment by skothari-tibco** [comment]
I think its `flogo list`.

**Comment by akpuvvada** [comment]
That command, if I run it in folder created after we run `flogo create` it is not giving any output. If run in its parent folder, it is giving below response.

``Error validating project: not a valid flogo app project directory, missing 'src' diretory

**Comment by skothari-tibco** [comment]
The flogo list would give the detail description of the contributions (core is not a part.). Just `flogo create` would create a sample App with no contributions installed.

**Comment by akpuvvada** [comment]
No, no.
I mean I ran in the folder where my application is created - The JSON from the tutorial. Not empty project.

I was hoping I will get versions for all below which are part of the project:
 "imports": [
    "github.com/project-flogo/flow",
    "github.com/project-flogo/aws-contrib/trigger/lambda",
    "github.com/project-flogo/contrib/activity/actreturn",
    "github.com/project-flogo/contrib/activity/log",
    "github.com/project-flogo/contrib/function/string"
  ],
