### ISSUE TITLE
Build issue in Flows with Lambda Trigger

### ISSUE THREAD

**Issue by akpuvvada** [project-flogo/cli#103]
Getting below error when trying to build app developed from FLogo UI.
I tried adding missing things comparing to the Sample given in Tutorial at https://tibcosoftware.github.io/flogo/faas/how-to/.
Attached both JSONs in Zip file.

[aws_lambda_rest_poc_ini_2_updated.zip](https://github.com/project-flogo/cli/files/3897864/aws_lambda_rest_poc_ini_2_updated.zip)

```
flogo build -e --shim aws_lambda_trigger --verbose
Embedding configuration in application...
Creating shim support files...
Preparing shim...
Using build.go to build shim......
Running build script for the Lambda trigger
Cleaning up previous executables
Building a new handler file
# github.com/project-flogo/flow/definition
C:\Users\206503518\go\pkg\mod\github.com\project-flogo\flow@v0.9.4\definition\resolve.go:14:16: undefined: "github.com/project-flogo/core/data/resolve".PropertyResolver
exit status 2Zipping the new handler file
Failed to compress file: open C:\Users\206503518\OneDrive - NBCUniversal\My Documents\Desktop\Flogo\AWS_POC\POC2\AWS_Lambda_REST_POC_INI2\src\handler: The system cannot find the file specified.Cleaning up shim support files...
```

**Comment by skothari-tibco** [comment]
Cam you try running `flogo update github.com/project-flogo/flow@master` ?

**Comment by akpuvvada** [comment]
I did that, below is the sequence of commands I am trying every-time.

```
cd C:\Flogo\AWS_POC\POC2
set http_proxy=http://proxy.inbcu.com:80/
flogo create -f aws_lambda_rest_poc_ini_2.json AWS_Lambda_REST_POC_INI2
cd AWS_Lambda_REST_POC_INI2
flogo update github.com/project-flogo/core@master
flogo build -e --shim aws_lambda_trigger
```

**Comment by skothari-tibco** [comment]
It's "flow".

**Comment by akpuvvada** [comment]
ok, let me try that.

What is the difference?

**Comment by skothari-tibco** [comment]
Did that help?

**Comment by akpuvvada** [comment]
Yes, it worked.

Thanks, Samip.

What is the difference?

**Comment by skothari-tibco** [comment]
The "core" is the engine that runs the flogo App. It combines the triggers and action/activities specified in JSON file and runs them. "Flow" on the other hand is a type of action that is called by the trigger to process the event. Hope that helps.

**Comment by agg24ankit** [comment]
@skothari-tibco What is the solution for this. I am also getting same error

**Comment by agg24ankit** [comment]
This is my error
D:\Flogo\app\myapp2>flogo build -e --shim aws_lambda_trigger --verbose
Embedding configuration in application...
Creating shim support files...
Preparing shim...
Using build.go to build shim......
Running build script for the Lambda trigger
Cleaning up previous executables
Building a new handler file
go: main: package github.com/aws/aws-lambda-go/lambda imported from implicitly required module; to add missing requirements, run:
        go get github.com/aws/aws-lambda-go/lambda@v1.10.0
exit status 1Zipping the new handler file
Failed to compress file: open D:\Flogo\app\myapp2\src\handler: The system cannot find the file specified.Cleaning up shim support files...
