### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/cli#15]
When I try to create a flogo project in my windows environment, I get the following error:

```
>flogo create testing
Creating Flogo App: testing
installing core
Error: open examples\engine\flogo.json: The system cannot find the path specified.
```

my go version :
`go version go1.10.5 windows/amd64`

My Windows environment:
`Windows 10 Pro @2018`

**Comment by apandurangi** [comment]
The same is an error when I try creating the project by `flogo create -f` mode.

**Comment by skothari-tibco** [comment]
Can you upgrade the Go version to 1.11 or above?

Thanks

**Comment by apandurangi** [comment]
@skothari-tibco Upgrading my go version to v 1.11+ solved the issue. Thank you. Can you please confirm if we need to consider go v1.11 as minimum supported version for the new cli?

**Comment by skothari-tibco** [comment]
Yeah, I have it in the docs. We will have the docs on the repo soon. In meanwhile you can refer this [link](https://github.com/skothari-tibco/cli)
