### ISSUE TITLE
Flogo list command fails with error

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/cli#18]
When I create a flogo engine using a legacy contributions it creates the engine but when I try to get the list of installed contributions I get the following error.

```
>flogo list
Error: open : The system cannot find the file specified.
```

Environment: Windows;
Application JSON used to create the engine: 
```
{
  "name": "echo",
  "description": "My flogo application description",
  "version": "1.0.0",
  "type": "flogo:app",
  "appModel": "1.0.0",
  "imports": [
    "github.com/project-flogo/contrib/trigger/rest",
    "github.com/TIBCOSoftware/flogo-contrib/activity/rest",
    "github.com/project-flogo/flow",
    "github.com/project-flogo/contrib/function/string"
  ]
}
```

**Comment by skothari-tibco** [comment]
Hey, 
Did you install the legacy activity after adding it to flogo.json?

**Comment by apandurangi** [comment]
I created the flogo project using the above mentioned application JSON. I got the following result:

```
>flogo create -f simple.json
Creating Flogo App: echo
installing core
Installed trigger:   github.com/project-flogo/contrib/trigger/rest
Installed activity:  github.com/TIBCOSoftware/flogo-contrib/activity/rest
Installed action:    github.com/project-flogo/flow
Installed function:  github.com/project-flogo/contrib/function/string
Installed Legacy Support
```

And I tried the **flogo list** command. I did not installed the legacy rest activity again after creating the flogo project.

**Comment by skothari-tibco** [comment]
I found the core issue behind this error. It's not able to find the path for `project-flogo/flow`. To find the path, it checks in the `go.mod` for versioning. Somehow when you install `TIBCOSoftware/flogo-contrib`the `project-flogo/flow` along with the version is not added in the `go.mod`. And this throws error. I'm not sure why this is happening. So currently you can manually add `flow` along with version in `go.mod` file, the issue should go away. Meanwhile I'll find out more on why this is happening.

**Comment by fm-tibco** [comment]
Fixed with PR https://github.com/project-flogo/cli/pull/21
