### ISSUE TITLE
flogo list does not populate the "ref"

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/cli#19]
When I list the installed contributions in a flogo project, I get all the details of the installed contributions, but the ref always is empty

```
[
  {
    "name": "flogo-rest",
    "type": "flogo:trigger",
    "descriptiom": "Simple REST Trigger",
    "ref": "",
    "path": "<my_GOWORKSPACE>\\pkg\\mod\\github.com\\project-flogo\\contrib@v0.9.0-alpha.3.0.20181217182402-f02d9316ced6\\trigger\\rest\\descriptor.json"
  },
  {
    "name": "flow",
    "type": "flogo:action",
    "descriptiom": "Simple Flow Action",
    "ref": "",
    "path": "<my_GOWORKSPACE>\\pkg\\mod\\github.com\\project-flogo\\flow@v0.9.0-alpha.3\\descriptor.json"
  },
  {
    "name": "strings",
    "type": "flogo:function",
    "descriptiom": "String Functions",
    "ref": "",
    "path": "<my_GOWORKSPACE>\\pkg\\mod\\github.com\\project-flogo\\contrib@v0.9.0-alpha.3.0.20181217182402-f02d9316ced6\\function\\string\\descriptor.json"
  }
]
```

Environment: Windows 10

**Comment by skothari-tibco** [comment]
There is no `ref` in the descriptor.json. However there's `homepage`, is that the thing you would like to see?

**Comment by fcastill** [comment]
`homepage` links to the documentation of the contribution while our need for `ref` is to uniquely identify a contribution so when inspecting an app in a flogo.json we can relate a trigger or a task to their corresponding descriptor.

Maybe we should add the ref to the descriptor.json in project-flogo/contrib? Or is there a way to infer the refs?

What do you think @fm-tibco?

**Comment by debovema** [comment]
Hi,

I let you fix the ref part.

I think that displaying the homepage would be great. I created a PR #20 for this purpose.
