### ISSUE TITLE
Windows - Building application fails for different OS and ARCH

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/cli#29]
While following [steps](https://tibcosoftware.github.io/flogo/labs/edison-iot/#building-an-app) to build application for different GOOS and GOARCH I get the following error.

```
\flogo-experiment\dev-engine\Empty app>SET GOOS=linux

\flogo-experiment\dev-engine\Empty app>SET GOARCH=amd64

\flogo-experiment\dev-engine\Empty app>flogo build --verbose
Path to exe is  \flogo-experiment\dev-engine\Empty app\src\main.exe
Error: failed to build application, run with --verbose to see details
```

**Comment by apandurangi** [comment]
I have created my application using the following JSON:
```
{
  "name": "flogo-web",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "Empty flogo app",
  "triggers": [],
  "actions": [
    {
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}
```

Later installed the following pallette: 
```
[
  {
    "name": "flow",
    "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
  },
  {
    "name": "log",
    "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/log"
  },
  {
    "name": "rest",
    "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/rest"
  },
  {
    "name": "rest",
    "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest"
  }
]
```

**Comment by apandurangi** [comment]
I am using the following flogo.json: 
```
{
  "name": "Empty app",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "Empty flogo app",
  "triggers": [],
  "actions": [
    {
      "ref": "github.com/project-flogo/flow"
    }
  ]
}
```

Later installed the following pallette: 
```
[
  {
    "name": "flow",
    "ref": "github.com/project-flogo/flow"
  },
  {
    "name": "log",
    "ref": "github.com/project-flogo/contrib/activity/log"
  },
  {
    "name": "rest",
    "ref": "github.com/project-flogo/contrib/activity/rest"
  },
  {
    "name": "rest",
    "ref": "github.com/project-flogo/contrib/trigger/rest"
  }
]
```

**Comment by apandurangi** [comment]
@skothari-tibco I am not getting an error now, but I am always get an `.exe` executable as mine it is a windows environment. Should it not output the binary based on the `env` OS value?

**Comment by skothari-tibco** [comment]
What's the output of verbose?

**Comment by apandurangi** [comment]
> What's the output of verbose?

\flogo-experiment\dev-engine\Empty app>flogo build -o -e --verbose
Path to exe is  \flogo-experiment\dev-engine\Empty app\src\main

**Comment by skothari-tibco** [comment]
Yeah.. so since you have GOOS to Linux it would create a "main" executable file. Rename it to `Empty app` and copy it to your bin folder. If you don't set GOOS to linux it would create a `.exe` file

**Comment by apandurangi** [comment]
> Yeah.. so since you have GOOS to Linux it would create a "main" executable file. Rename it to `Empty app` and copy it to your bin folder. If you don't set GOOS to linux it would create a `.exe` file

Yep. But my GOOS is set to linux but I see a `Empty app.exe` in bin folder. I checked with v0.5.8 version and it actually copies a binary file

**Comment by skothari-tibco** [comment]
Alright. I see where the error is. I forgot to change the executable path to work with cross compilation.
