### ISSUE TITLE
The CLI output should indicate what version of core is being installed if specified with `--cv`

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/cli#47]
When using `--cv` to indicate a specific version of core, the CLI should display what version is being installed to avoid any confusion.

```
flogo create --cv master -f myapp.json
Creating Flogo App: MyApp
installing core
```

**Comment by fm-tibco** [comment]
Im confused by this..  isn't this redundant?

**Comment by mellistibco** [comment]
I guess not just specifically when you specify the version, just thinking it would be nice to display the version of core that is being installed.

**Comment by fm-tibco** [comment]
I guess definitely makes sense for "latest"
