### ISSUE TITLE
Cannot create the example app.

### ISSUE THREAD

**Issue by matthewcummings** [project-flogo/cli#65]
I've tried running `flogo create -f flogo.json myApp` per the ReadMe but it fails with this error (and extra logging from --verbose):

Creating Flogo App: myApp
Setting up app directory: /home/matthew/repos/mattdevops/flogo-demo/myApp
go: creating new go.mod: module main
Installing: github.com/project-flogo/core@latest
all modules verified
Error creating project: open pkg/mod/github.com/project-flogo/core@v0.9.0-beta.3/examples/engine/main.go: no such file or directory

This is with Ubuntu 18.04 + go 1.12.1

**Comment by skothari-tibco** [comment]
I see that the GOPATH hasn't been set. Can you confirm that?

**Comment by matthewcummings** [comment]
Yes, that was it @skothari-tibco.
