### ISSUE TITLE
With `GO111MODULE=on` cli fails to install plugins

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/cli#85]
The CLI will fail to install plugins because `$GOPATH/src/github.com/project-flogo/cli` is no longer present, it is now `$GOPATH/pkg/mod/github.com/project-flogo` (maybe someplace else also?)... This is also an issue with Go 1.13, as GO111MODULE is on by default.

See the error below:

```bash
Matts-MacBook-Pro-5:~ mellis$ export GO111MODULE=on
Matts-MacBook-Pro-5:~ mellis$ go get github.com/project-flogo/cli/...
go: finding github.com/project-flogo/cli/... latest
go: downloading github.com/project-flogo/cli v0.9.0
go: extracting github.com/project-flogo/cli v0.9.0
go get github.com/project-flogo/cli/...: no matching versions for query "latest"
Matts-MacBook-Pro-5:~ mellis$ flogo plugin install github.com/project-flogo/cli-plugins/devtool
2019/09/16 08:54:28 chdir /Users/mellis/go/src/github.com/project-flogo/cli: no such file or directory
```

**Comment by skothari-tibco** [comment]
In the release notes `https://golang.org/doc/go1.13#introduction`  
```The GO111MODULE environment variable continues to default to auto ....``` 
Hence, it's still not on by default. I think you might have confused that with 
``` ....the auto setting now activates the, module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src``` . Which is if you are in GOPATH/src you no longer need `GO111MODULE=on` which was the case earlier.  
Since we are trying to install CLI as a `src` or a `repo` rather than a `pkg` or a `mod`, we do need 
`GO111MODULE=""` .

Hope this helps.

**Comment by mellistibco** [comment]
When I tried a fresh install of go 1.13 I get the same error referenced in my original issue. Also, we cannot expect anyone to manually set GO111MODULE to off, thats not a solution.

**Comment by mellistibco** [comment]
Also, not everyone who uses Flogo will be familiar with Go, so we shouldn't really expect that as an answer. We'll need to fix the CLI to find the right path for the src so that the plugin can be installed.

**Comment by skothari-tibco** [comment]
@mellistibco, Just to double check, are you sure that GO111module was not "on" after a fresh install ? I used a fresh go.1.13 image and I do not face this issue.

**Comment by mellistibco** [comment]
Pretty sure but will double check. Did you ensure that you don't have $GOPATH/src/github.com/project-flogo/cli already on your machine? If that is there, then you wont face any issues, obviously...

**Comment by mellistibco** [comment]
I also just tried:
```bash
Matts-MacBook-Pro-5:~ mellis$ export GO111MODULE=auto
Matts-MacBook-Pro-5:~ mellis$ flogo plugin install github.com/project-flogo/cli-plugins/devtool
2019/09/16 10:24:17 chdir /Users/mellis/go/src/github.com/project-flogo/cli: no such file or directory
```bash

**Comment by skothari-tibco** [comment]
I used a completely new docker image with version 1.13. I did not face that issue. The only issue is  GO111MODULE to on during installation. There's no issue if you set it to "on" or "off" or "" after that.

**Comment by mellistibco** [comment]
@skothari-tibco yes, with go111module set to on during the installation of the CLI (go get), that's the root of the issue, as the CLI is basically coded to look in `$GOPATH/src/github.com/project-flogo/cli` for the source so that the plugin can be installed... That is the issue. We cannot tell people to manually set GO111MODULE to "" before fetching the Flogo CLI to work around an issue...

**Comment by mellistibco** [comment]
closing as this was resolved in the last pr
