### ISSUE TITLE
Build does not copy the flogo.json to the bin dir

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/cli#9]
After a successful `flogo build` when I execute bin/TheApp the following error is thrown:

```
 ~/flogo-apps/Example  flogo-new build                                                                                                    ~/flogo-apps/Example  cd bin
 ~/flogo-apps/Example/bin  ./Example

16:09:14 2018-10-25 16:09:16.344 ERROR  [main-engine] - Failed to create engine: open flogo.json: no such file or directory
```

**Comment by fm-tibco** [comment]
fixed in latest code, if not embedded, it engine looks for flogo.json in current directory, if not found looks in parent directory.  This prevents the need to have multiple copies of flogo.json when developing an application.
