### ISSUE TITLE
How to Configure Proxy

### ISSUE THREAD

**Issue by akpuvvada** [project-flogo/cli#93]
I am trying to follow the steps in https://tibcosoftware.github.io/flogo/faas/how-to/ to build a Flogo app from CLI.
I am getting proxy related errors.
I tried setting Env properties using below commands in the same session.
```
  set https_proxy=http:proxy.inbcu.com:80/
  set http_proxy=http://proxy.inbcu.com:80/
```

After setting the above proxy, getting different error.
Please help.

**Error without proxy**:
```
Creating Flogo App: myapp
Installing: github.com/project-flogo/core@latest
Error creating project: go get github.com/project-flogo/core@latest: module github.com/project-flogo/core: Get https://proxy.golang.org/github.com/project-flogo/core/@v/list: dial tcp: lookup proxy.golang.org: no such host
```

**Error with Proxy**:
```
Creating Flogo App: myapp
Installing: github.com/project-flogo/core@latest
Error creating project: go get github.com/project-flogo/core@latest: module github.com/project-flogo/core: Get https://proxy.golang.org/github.com/project-flogo/core/@v/list: proxyconnect tcp: dial tcp :80: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by mellistibco** [comment]
Hi @akpuvvada it looks like the DNS server you're using is unable to resolve proxy.golang.org. TIBCOSoftware/flogo#514

**Comment by mellistibco** [comment]
Can you try disabling the golang proxy? Set the following environment variable `GOPROXY` to `direct`:
```bash
export GOPROXY=direct
```

**Comment by akpuvvada** [comment]
Hi Matt, that did not help either. Got same error.

**Comment by skothari-tibco** [comment]
I see that you have `http_proxy` , I think that's what which may be causing error . May be  `set https_proxy=http://proxy.inbcu.com:80/` . Though not completely sure.

**Comment by akpuvvada** [comment]
> 
> 
> I see that you have `http_proxy` , I think that's which may be causing error . May be
> `set https_proxy=http://proxy.inbcu.com:80/` . Though not completely sure.

Hi Samip, thanks that worked.
May I know how to make build work from Flogo UI?

Thanks
Anil

**Comment by skothari-tibco** [comment]
Do you mean, how would you build flogo app from UI ?

**Comment by akpuvvada** [comment]
No, I am getting an error while trying to build App from UI. When I check in Flogo container logs, it is giving similar error as when I don't use `set proxy_http` in CLI. I have Proxy set-up on Docker settings. Not sure where else to set-up.

**Comment by akpuvvada** [comment]
BTW, I am able to build the Flogo app if I am connected to my home network. I need to be able to do that from office / corp network.

**Comment by skothari-tibco** [comment]
@fcastill

**Comment by fcastill** [comment]
It looks like this question is answered and the one about the Web UI was already answered in TIBCOSoftware/flogo#514. Can we close this issue?
